routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('console', App\Http\Controllers\ConsoleController::class)
->except(['show'])
->middleware('auth');

Route::resource('game', App\Http\Controllers\GameController::class)
->middleware('auth')
->except(['show']);

Route::resource('metadata', App\Http\Controllers\MetadataController::class)
->middleware('auth')
->except(['show']);

Route::get('/home', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Metadata.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Metadata extends Model
{
    use HasFactory;

    protected $fillable = ['game_id', 'user_id', 'rating', 'comment'];

    public function game(){

        return $this->belongsTo(Game::class);
    }
}

app/Http/Controllers/MetadataController.php
<?php

namespace App\Http\Controllers;

use App\Models\Game;
use App\Models\Metadata;
use Illuminate\Http\Request;

class MetadataController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        return view('metadata.index', ['metadatas' => Metadata::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('metadata.create', ['games' => Game::all()]);

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            
            'game_id' => 'required',
            'purchase_date' => 'required',
            'calification' => 'required',
            'tags' => 'required',
            'times_played' => 'required',
            'date_completed' => 'required',
            'time_of_completion' => 'required',
            
        ]);

        $metadata = new Metadata();
        $metadata->game_id = $request->game_id;
        $metadata->purchase_date = $request->purchase_date;
        $metadata->calification = $request->calification;
        $metadata->tags = $request->tags;
        $metadata->times_played = $request->times_played;
        $metadata->date_completed = $request->date_completed;
        $metadata->time_of_completion = $request->time_of_completion;
        $metadata->have_it = $request->have_it;
        $metadata->played = $request->played;
        $metadata->playing = $request->playing;
        $metadata->save();
        return redirect()->route('metadata.index')->with('success', 'Metadata created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Metadata $metadata)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Metadata $metadata)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Metadata $metadata)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Metadata $metadata)
    {
        //
    }
}

resources/views/metadata/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex items-center justify-center h-screen">
        <div class="bg-white p-8 rounded shadow-md">
            <h2 class="text-2xl font-semibold mb-6">Add Metadata</h2>
            <form action="{{ route('metadata.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mb-4">
                    <label for="game_id" class="block text-sm font-medium text-gray-700">Game</label>
                    <select name="game_id" id="game_id" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                        @foreach ($games as $game)
                            <option value="{{ $game->id }}">{{ $game->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-4">
                    <label for="purchase_date" class="block text-sm font-medium text-gray-700">Purchase Date</label>
                    <input type="date" name="purchase_date" id="purchase_date"
                        class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                </div>
                <div class="mb-4">
                    <label for="calification" class="block text-sm font-medium text-gray-700">Calification</label>
                    <input type="text" name="calification" id="calification"
                        class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                </div>
                <div class="mb-4">
                    <label for="tags" class="block text-sm font-medium text-gray-700">tags</label>
                    <textarea name="tags" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm"></textarea>

                </div>
                <div class="mb-4">
                    <label for="times_played" class="block text-sm font-medium text-gray-700">Times played</label>
                    <input type="number" name="times_played" id="times_played"
                        class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                </div>

                <div class="mb-4">
                    <label for="date_completed" class="block text-sm font-medium text-gray-700">Date completed</label>
                    <input type="date" name="date_completed" id="date_completed"
                        class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                </div>

                <div class="mb-4">
                    <label for="notes" class="block text-sm font-medium text-gray-700">Notes</label>
                    <textarea name="notes" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm"></textarea>
                </div>

                <div class="mb-4">
                    <label for="time_of_completion" class="block text-sm font-medium text-gray-700">time_of_completion</label>
                    <input type="number" name="time_of_completion" id="time_of_completion" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">

                </div>


                <!-- Add input fields for the rest of the fields in the migration here -->
                <div class="mb-4">
                    <label for="have_it" class="block text-sm font-medium text-gray-700">Do you have it?</label>
                    <input type="checkbox" name="have_it" id="have_it" class="mt-1">
                </div>
                <div class="mb-4">
                    <label for="played" class="block text-sm font-medium text-gray-700">Have you played it?</label>
                    <input type="checkbox" name="played" id="played" class="mt-1">
                </div>
                <div class="mb-4">
                    <label for="playing" class="block text-sm font-medium text-gray-700">Are you currently playing
                        it?</label>
                    <input type="checkbox" name="playing" id="playing" class="mt-1">
                </div>
                <button type="submit" class="bg-blue-500 text-black hover:bg-blue-700 py-2 px-4 rounded">Add Metadata</button>
            </form>
        </div>
    </div>
@endsection