routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('console', App\Http\Controllers\ConsoleController::class)
->except(['show'])
->middleware('auth');

Route::resource('game', App\Http\Controllers\GameController::class)
->middleware('auth')
->except(['show']);

Route::resource('metadata', App\Http\Controllers\MetadataController::class)
->middleware('auth')
->except(['show']);

Route::get('/home', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'developer', 'release_date', 'console_id'];


    public function console(){
        return $this->belongsTo(Console::class);
    }

    public function metadata(){
        
        return $this->hasOne(Metadata::class);
    }

}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Models\Console;
use App\Models\Game;
use Illuminate\Http\Request;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        return view('game.index', ['games' => Game::all()], ['consoles' => Console::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('game.create', ['consoles' => Console::all()]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'console_id' => 'required',
            'release_date' => 'required',   
            'image' => 'required',
            'developer' => 'required',
            'publisher' => 'required',
            'franquice' => 'required',
            'genere' => 'required',
            'theme' => 'required',
            'clasification' => 'required',
            'type' => 'required',

        ]);

        $game = new Game();
        $game->console_id = $request->console_id;
        $game->name = $request->name;
        $game->description = $request->description;
        $game->release_date = $request->release_date;
        $game->image = $request->image;
        $game->developer = $request->developer;
        $game->publisher = $request->publisher;
        $game->franquice = $request->franquice;
        $game->genere = $request->genere;
        $game->theme = $request->theme;
        $game->clasification = $request->clasification;
        $game->type = $request->type;
        $game->save();
        return redirect()->route('game.index')->with('success', 'Game created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Game $game)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Game $game)
    {
        //
        return view('game.edit', ['game' => $game], ['consoles' => Console::all()]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Game $game)
    {
        //
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'developer' => 'required',
            'publisher' => 'required',
            'console_id' => 'required',
            'release_date' => 'required',
            'image' => 'required',
        ]);

        $game->update([
            'name' => $request->name,
            'description' => $request->description,
            'developer' => $request->developer,
            'publisher' => $request->publisher,
            'console_id' => $request->console_id,
            'release_date' => $request->release_date,
            'image' => $request->image,

        ]);

        return redirect()->route('game.index')->with('success', 'Game updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Game $game)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/game/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl dark:text-gray-900 leading-tight">
            {{ __('Games') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-xl sm:rounded-lg">
              <!--  <x-welcome /> -->
              @livewire('create-game')

            </div>
        </div>
    </div>
</x-app-layout>

resources/views/game/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl dark:text-gray-900 leading-tight">
            {{ __('Games') }}
        </h2>
    </x-slot>

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6 bg-white border-b border-gray-200">
                <form action="{{ route('game.update', $game->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT') {{-- Add this line to indicate that it's a PUT request for updating --}}
                    
                    <div class="mb-4">
                        <label for="console_id" class="block text-sm font-medium text-gray-700">Console</label>
                        <select name="console_id" id="console_id" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @foreach ($consoles as $console)
                                <option value="{{ $console->id }}" {{ old('console_id', $game->console_id) == $console->id ? 'selected' : '' }}>{{ $console->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-4">
                        <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                        <input type="text" name="name" id="name" value="{{ old('name', $game->name) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                        @error('name')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="mb-4">
                        <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                        <textarea name="description" id="description" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">{{ old('description', $game->description) }}</textarea>
                        @error('description')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="mb-4">
                        <label for="release_date" class="block text-sm font-medium text-gray-700">Release Date</label>
                        <input type="date" name="release_date" id="release_date" value="{{ old('release_date', $game->release_date) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                    </div>
                    <div class="mb-4">
                        <label for="developer" class="block text-sm font-medium text-gray-700">Developer</label>
                        <input type="text" name="developer" id="developer" value="{{ old('developer', $game->developer) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                    </div>
                    <div class="mb-4">
                        <label for="publisher" class="block text-sm font-medium text-gray-700">Publisher</label>
                        <input type="text" name="publisher" id="publisher" value="{{ old('publisher', $game->publisher) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                    </div>
                    
                    <div class="mb-4">
                        <label for="image" class="block text-sm font-medium text-gray-700">Image</label>
                        <input type="file" name="image" id="image" value="{{ old('image', $game->image) }}" accept="image/*" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                        @error('image')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>
                    <button type="submit" class="bg-blue-500 text-black hover:bg-blue-700 py-2 px-4 rounded">Update</button>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/game/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Games') }}
        </h2>
    </x-slot>
    
    <div class="py-12">
        <div class="  lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-xl sm:rounded-lg">
              <!--  <x-welcome /> -->
              @livewire('show-games')

            </div>
        </div>
    </div>
</x-app-layout>