routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('console', App\Http\Controllers\ConsoleController::class)
->except(['show'])
->middleware('auth');

Route::resource('game', App\Http\Controllers\GameController::class)
->middleware('auth')
->except(['show']);

Route::resource('metadata', App\Http\Controllers\MetadataController::class)
->middleware('auth')
->except(['show']);

Route::get('/home', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Console.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Console extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'manufacturer', 'release_date'];

    public function games(){
        return $this->hasMany(Game::class);
    }

    public function user(){
        return $this->belongsTo(User::class);

    }

    
}

app/Http/Controllers/ConsoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Console;
use Illuminate\Http\Request;

class ConsoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        return view('console.index', ['consoles' => Console::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('console.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name' => 'required',   
            'manufacturer' => 'required',
            'release_date' => 'required',
        ]);

        $console = new Console();
        $console->user_id = auth()->user()->id;
        $console->name = $request->name;
        $console->manufacturer = $request->manufacturer;
        $console->release_date = $request->release_date;
        $console->save();
        return redirect()->route('console.index')->with('success', 'Console created successfully.');
        
    }

    /**
     * Display the specified resource.
     */
    public function show(Console $console)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Console $console)
    {
        
        return view('console.edit', ['console' => $console]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Console $console)
    {
         // Validar los datos del formulario
    $request->validate([
        'name' => 'required|string|max:255',
        'manufacturer' => 'required|string|max:255',
        'release_date' => 'required|date',
    ]);

    // Actualizar los datos del modelo Console con los datos del formulario
    $console->update([
        'name' => $request->input('name'),
        'manufacturer' => $request->input('manufacturer'),
        'release_date' => $request->input('release_date'),
        // Puedes agregar más campos según sea necesario
    ]);

    // Redireccionar a la vista o ruta deseada después de la actualización
    return redirect()->route('console.index')->with('success', 'Console updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Console $console)
    {
        //

        $console->delete();
        
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/console/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl  dark:text-gray-900 leading-tight">
            {{ __('Consoles') }}
        </h2>
    </x-slot>
    
  
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('console.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @php
                            $user = auth()->user();
                        @endphp
                        <input type="hidden" id="user_id" name="user_id" value="{{ $user->id }}">
                        <div class="mb-4">
                            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                            <input type="text" name="name" id="name" value="{{ old('name') }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @error('name')
                                <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="mb-4">
                            <label for="manufacturer" class="block text-sm font-medium text-gray-700">Manufacturer</label>
                            <input type="text" name="manufacturer" id="manufacturer" value="{{ old('manufacturer') }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @error('manufacturer')
                                <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="mb-4">
                            <label for="release_date" class="block text-sm font-medium text-gray-700">Release Date</label>
                            <input type="date" name="release_date" id="release_date" value="{{ old('release_date') }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @error('release_date')
                                <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                            @enderror
                        </div>
                        <button type="submit" class="bg-blue-900 text-black hover:bg-blue-700 py-2 px-4 rounded ">Create</button>
                    </form>
                </div>
            </div>
        </div>
    
</x-app-layout>

resources/views/console/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl  dark:text-gray-900 leading-tight">
            {{ __('Consoles') }}
        </h2>
    </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('console.update', $console->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT') {{-- Agregar esta línea para indicar que es una solicitud PUT para la actualización --}}
                        
                        <div class="mb-4">
                            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                            <input type="text" name="name" id="name" value="{{ old('name', $console->name) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @error('name')
                                <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="mb-4">
                            <label for="manufacturer" class="block text-sm font-medium text-gray-700">Manufacturer</label>
                            <input type="text" name="manufacturer" id="manufacturer" value="{{ old('manufacturer', $console->manufacturer) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @error('manufacturer')
                                <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="mb-4">
                            <label for="release_date" class="block text-sm font-medium text-gray-700">Release Date</label>
                            <input type="date" name="release_date" id="release_date" value="{{ old('release_date', $console->release_date) }}" class="mt-1 p-2 block w-full border-gray-300 rounded-md shadow-sm">
                            @error('release_date')
                                <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                            @enderror
                        </div>
                        <button type="submit" class="bg-blue-900 text-black hover:bg-blue-700 py-2 px-4 rounded">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/console/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Consoles') }}
        </h2>
    </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-xl sm:rounded-lg">
              <!--  <x-welcome /> -->
              @livewire('show-posts')

            </div>
        </div>
    </div>
</x-app-layout>